// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vldqiteuwzvwfhfoyiel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZHFpdGV1d3p2d2ZoZm95aWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njk0OTYsImV4cCI6MjA2NjQ0NTQ5Nn0.aSfHV0GCruB3YS5utCFUBfJrm5MUu-3cUFKqTU9tw_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);