name: Sync value-match-finder-form into financial-institutions-marketing-tool

on:
  workflow_dispatch:        # Manual trigger option
  schedule:
    - cron: '0 3 * * *'     # Daily at 3am UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout financial-institutions-marketing-tool
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Add value-match-finder-form as remote and fetch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add value-match https://github.com/Jai04090/value-match-finder-form.git
          git fetch value-match

      - name: Merge and Push
        run: |
          git merge value-match/main --allow-unrelated-histories -m "Automated merge from value-match-finder-form"
          git push origin main
        continue-on-error: true

      - name: Open PR if Merge Fails
        if: failure()
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated sync from value-match-finder-form"
          title: "Sync from value-match-finder-form"
          body: "This PR brings in the latest changes from value-match-finder-form."
